// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="packet_generator,hls_ip_2015_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

module packet_generator (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_V,
        mac_destination_V,
        mac_source_V,
        length_V,
        ip_destination_V,
        ip_source_V,
        source_port_V,
        destination_port_V,
        inter_packet_gap_V,
        num_pkt_V,
        continuos_V
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] out_V;
input  [47:0] mac_destination_V;
input  [47:0] mac_source_V;
input  [15:0] length_V;
input  [31:0] ip_destination_V;
input  [31:0] ip_source_V;
input  [15:0] source_port_V;
input  [15:0] destination_port_V;
input  [31:0] inter_packet_gap_V;
input  [15:0] num_pkt_V;
input  [0:0] continuos_V;




assign ap_done = ap_start;
assign ap_idle = ap_const_logic_1;
assign ap_ready = ap_start;


endmodule //packet_generator

