// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _packet_generator_HH_
#define _packet_generator_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct packet_generator : public sc_module {
    // Port declarations 15
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > out_V;
    sc_in< sc_lv<48> > mac_destination_V;
    sc_in< sc_lv<48> > mac_source_V;
    sc_in< sc_lv<16> > length_V;
    sc_in< sc_lv<32> > ip_destination_V;
    sc_in< sc_lv<32> > ip_source_V;
    sc_in< sc_lv<16> > source_port_V;
    sc_in< sc_lv<16> > destination_port_V;
    sc_in< sc_lv<32> > inter_packet_gap_V;
    sc_in< sc_lv<16> > num_pkt_V;
    sc_in< sc_lv<1> > continuos_V;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    packet_generator(sc_module_name name);
    SC_HAS_PROCESS(packet_generator);

    ~packet_generator();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
